# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoCall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoCall
  pod 'Floaty', '~> 4.2.0'
  pod 'AGEVideoLayout', '~> 1.0.2'
  pod 'CocoaAsyncSocket', '7.6.5'
 pod 'AgoraRtcEngine_iOS', '4.2.2'
  target 'VideoCallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoCallUITests' do
    # Pods for testing
  end

end
